### ISSUE TITLE
[]*strtuct 识别有问题  可把* 替换掉

### ISSUE THREAD

**Issue by gaotangqi** [zeromicro/goctl-swagger#1]
![image](https://user-images.githubusercontent.com/17448169/104703440-4a467b80-5752-11eb-8142-bc29c32cedd3.png)
 

"list": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/*CardShelf"
          }
        }
      },

 "CardShelf": {
      "type": "object",
      "properties": {
        "shelfId": {
          "type": "integer",
          "format": "int64"
        },
        "brandId": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "cardType": {
          "type": "integer",
          "format": "int64"
        },
        "cardImg": {
          "type": "string"
        },

**Comment by MaxToby** [comment]
已处理
