### ISSUE TITLE
tag 重复被写到swagger json required属性中

### ISSUE THREAD

**Issue by githubzhaoqian** [zeromicro/goctl-swagger#12]
api 类型tag 如果未加optional 并且有过个相同tag值会被多次写入swagger json required属性中

```
UserPerfectInfo {
		UName  string `json:"uname" form:"uname" validate:"required"`   //用户名
		Avatar string `json:"avatar" form:"avatar" validate:"required,optional"` //头像
	}
```

还有validate 是给其他插件用的,但是要加入一个optional才能排除否则也会也到swagger json required属性中没有发现有什么影响

**Comment by MaxToby** [comment]
80775cf7efdb45b3ef4074cf6484ab145faee8b5 这里需要一个去重复的操作，感谢提醒。
