### ISSUE TITLE
与gin-swagger使用较大差距

### ISSUE THREAD

**Issue by ldmid666** [zeromicro/goctl-swagger#13]
无法兼容gin-swagger，与gin-swagger使用有较大差别，导致不得不把go-zero的router改成gin
为了更方便使用gin-swagger。
go-zero能不能在不变更router的情况下，兼容gin-swagger的使用。
![image](https://user-images.githubusercontent.com/49946804/138681017-8f4d6f5c-2b7e-4345-9031-a183f71689b8.png)

gin-swagger的依赖文件

**Comment by MaxToby** [comment]
gin-swagger是需要自己在方法上写注释的吧。 这个项目是根据api文件生成的。 使用swagger-ui查看没有任何差别
