### ISSUE TITLE
是否可以生成yaml

### ISSUE THREAD

**Issue by pz2147** [zeromicro/goctl-swagger#15]
是否可以生成yaml格式

**Comment by MaxToby** [comment]
目前不可以的，这个不是调用 swagger-generator来生成的

**Comment by shyandsy** [comment]
我改成yaml encoder之后，yaml文件有问题
我还没找到原因

**Comment by shyandsy** [comment]
我改成yaml encoder之后，yaml文件有问题
我还没找到原因
