### ISSUE TITLE
jwt: Auth声明的api没有生成Headers的Authorization参数

### ISSUE THREAD

**Issue by happyue** [zeromicro/goctl-swagger#36]

**Comment by Tymon42** [comment]
```
type meReq {
	Authorization string `header:"Authorization"`
}
```
这样的 header 经过 goctl-swagger 生成文档会成为 query 参数

**Comment by Tymon42** [comment]
这是如何解决的呢？

**Comment by happyue** [comment]
> 这是如何解决的呢？

我自己修改了generate/parser.go的代码，我是为了生成的json导入到YAPI中，所以没有提pr.
代码关键字：
`group.Annotation.Properties["jwt"] `
