### ISSUE TITLE
是否可以新增隐藏models ui模块参数

### ISSUE THREAD

**Issue by xiaocode337317439** [zeromicro/goctl-swagger#40]
是否可以新增隐藏models ui模块参数，以及默认打开指定的分组或者默认全部折叠

**Comment by MaxToby** [comment]
不是很明白，方便举例说明一下吗？

**Comment by xiaocode337317439** [comment]
> 不是很明白，方便举例说明一下吗？

生成的swagger ui页面 最下面是 model显示部分，上面是api分组部分，model ui这部分可以增加参数控制不生成。
