### ISSUE TITLE
http返回时，怎么使用swagger统一增加数据包装

### ISSUE THREAD

**Issue by Danny5487401** [zeromicro/goctl-swagger#47]
[go-zero 官方文档](https://go-zero.dev/cn/docs/advance/error-handle) 增加了error 统一分装
```go
{
  "code": 0,
  "msg": "successful",
  "data": {
    ....
  }
}
```

怎么使用插件swagger统一生成封装后的go代码？

**Comment by htlhenry** [comment]
我这里也有同样的，目前没有具体实现

**Comment by xuanskyer** [comment]
same q

**Comment by MaxToby** [comment]
#55 已经有朋友pr了。你看看是否满足需求

**Comment by Danny5487401** [comment]
> #55 已经有朋友pr了。你看看是否满足需求

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/64348131/204093490-c3f4d0b4-dce5-4ca3-ab27-0d1832b26c0d.png">

我要的是统一返回结构，{
  "code": 0,
  "msg": "successful",
  "data": {
    ....
  }
}
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/64348131/204093660-f56d36f3-d503-46d6-ab17-3da4d6b6b09e.png">

而不是仅仅501的时候返回err，200的时候也有err字段，只是为空
