### ISSUE TITLE
import导入的.api文件不能生成文档

### ISSUE THREAD

**Issue by greyireland** [zeromicro/goctl-swagger#6]
admin.api 引入其他的api
```
import "sys/user.api"
```

生成swagger报错
```
goctl api plugin -plugin goctl-swagger="swagger -filename user.json" -api admin.api -dir .
goctl-swagger: open /Users/wxd/go/bin/sys/user.api: no such file or directory

```

执行路径到$GOPATH/bin下面去了

**Comment by MaxToby** [comment]
您用的goctl版本是？

**Comment by greyireland** [comment]
goctl -v
goctl version 1.1.4 darwin/amd64

> 您用的goctl版本是？

**Comment by MaxToby** [comment]
@greyireland 升级Goctl 1.1.6 试试

**Comment by greyireland** [comment]
goctl -v
goctl version 1.1.6 darwin/amd64

goctl api plugin -plugin goctl-swagger="swagger -filename rb.json" -api rb.api -dir .

goctl-swagger: open /Users/wxd/go/bin/common.api: no such file or directory

GOPATH="/Users/wxd/go"
还是报错

**Comment by KwokGH** [comment]
我也遇到相同的问题

**Comment by MaxToby** [comment]
等待goctl解决

**Comment by kevwan** [comment]
fixed in goctl at master branch.
