### ISSUE TITLE
发现goctl-swagger无法支持uint32？

### ISSUE THREAD

**Issue by ldmid666** [zeromicro/goctl-swagger#7]
写完api文件后，用goctl-swagger生成json文件后，发现uint类型无法支持，如图所示，
![image](https://user-images.githubusercontent.com/49946804/115348563-56285a80-a1e5-11eb-8517-e63fcf0d059f.png)
然后生成的json如下：
![image](https://user-images.githubusercontent.com/49946804/115348601-63dde000-a1e5-11eb-8dce-ecd6b45df1f1.png)
int，string可以支持，其他类似是否支持我还没有测试。

**Comment by MaxToby** [comment]
收到，我会尽快处理。

**Comment by MaxToby** [comment]
已增加uint支持
