### ISSUE TITLE
cros是怎么回事 还没有请求到go-zero代码

### ISSUE THREAD

**Issue by gongzunyang** [zeromicro/goctl-swagger#70]
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
 报这样的错是怎么回事啊

**Comment by MaxToby** [comment]
跨域了。 
初始化rest的时候Cors就可以了。。
`rest.MustNewServer(c, rest.WithCors("*"))`
