### ISSUE TITLE
windows上生成swagger json 错误提示乱码

### ISSUE THREAD

**Issue by NLTRE** [zeromicro/goctl-swagger#73]
![image](https://user-images.githubusercontent.com/48545369/225966146-8de443fa-2cd6-4abe-b582-ea0420706c90.png)

**Comment by cro4k** [comment]
发现问题，找issue，有人提了，还是Closed，真好！打开一看，闭口不提怎么解决，真的让人很抓狂，最后还是靠自己。

Windows 下 GOPATH 路径不能有空格，也就是存放 goctl-swagger.exe 的路径不能有空格
