### ISSUE TITLE
生成的文档不能全局auth认证

### ISSUE THREAD

**Issue by yuanhao2015** [zeromicro/goctl-swagger#9]
生成的文档，不能全局认证，在访问的时候，无法在header 增加Authorization 信息
![image](https://user-images.githubusercontent.com/16285397/121645514-dc1aa080-cac6-11eb-8ef4-184b2777dcbd.png)
![2](https://user-images.githubusercontent.com/16285397/121645743-213ed280-cac7-11eb-8ace-0db209d03413.jpg)
建议需要验证的接口增加全局的属性参数
 "security":[
        {
        "apiKey":["global"]
        }
],
![image](https://user-images.githubusercontent.com/16285397/121645800-3287df00-cac7-11eb-96d2-a26565534ecf.png)

**Comment by ndzjx** [comment]
怎么解决的？
